#!/usr/bin/python

import time
import datetime

from Adafruit_LED_Backpack import SevenSegment

# ===========================================================================
# Date Day/Month
# ===========================================================================
segment = SevenSegment.SevenSegment(address=0x70)

# Initialize the display. Must be called once before using the display.
segment.begin()

print "Press CTRL+Z to exit"

# Continually update the date on a 4 char, 7-segment display
while(True):
  now = datetime.datetime.now()
  month = now.month
  day = now.day
  hour = now.hour
  minute = now.minute
  second = now.second
  

  segment.clear()
  # Set month
  segment.set_digit(0, int(month / 10))     # Tens
  segment.set_digit(1., month % 10)          # Ones
  # Set day
  segment.set_digit(2, int(day / 10))   # Tens
  segment.set_digit(3., day % 10)        # Ones
  
  # Write the display buffer to the hardware.  This must be called to
  # update the actual display LEDs.
  segment.write_display()

  # Wait a quarter second (less than 1 second to prevent colon blinking getting$
  time.sleep(0.25)
